//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMNI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".pdf")]
        public string DefaultPrintExtension {
            get {
                return ((string)(this["DefaultPrintExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-OMNI\\Application Data\\QIR Photos\\")]
        public string QIRPhotoDirectory {
            get {
                return ((string)(this["QIRPhotoDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-Wahpeton\\Prints\\")]
        public string PrintLocation {
            get {
                return ((string)(this["PrintLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WAXAS001")]
        public string ManageHostName {
            get {
                return ((string)(this["ManageHostName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/roi/CONTI.MAIN")]
        public string WCCOManageAccount {
            get {
                return ((string)(this["WCCOManageAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-Wahpeton\\Document Center\\Production\\")]
        public string WCCODocumentLocation {
            get {
                return ((string)(this["WCCODocumentLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.office365.com")]
        public string SmtpDefaultClient {
            get {
                return ((string)(this["SmtpDefaultClient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-OMNI\\Application Data\\temp\\")]
        public string omnitemp {
            get {
                return ((string)(this["omnitemp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1015")]
        public int CSISupplierNumber {
            get {
                return ((int)(this["CSISupplierNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-Wahpeton\\PublishedDocuments\\FORM5008 - Quality Incident Report.pd" +
            "f")]
        public string QIRDocument {
            get {
                return ((string)(this["QIRDocument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("contiwan.com")]
        public string EmailDomain {
            get {
                return ((string)(this["EmailDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vbty6^743[\\<tyF4")]
        public string EmailPassword {
            get {
                return ((string)(this["EmailPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-OMNI\\OMNI App\\OMNI.application")]
        public string omniAppLocation {
            get {
                return ((string)(this["omniAppLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-OMNI\\Application Data\\CMMS Documents\\")]
        public string CMMSDocumentLocation {
            get {
                return ((string)(this["CMMSDocumentLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-Wahpeton\\PublishedDocuments\\FORM5006E - Maintenance Request.pdf")]
        public string CMMSWorkOrderDocument {
            get {
                return ((string)(this["CMMSWorkOrderDocument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-Wahpeton\\QIR\\Photos")]
        public string QIRArchivePhotoDirectory {
            get {
                return ((string)(this["QIRArchivePhotoDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-Wahpeton\\QIR\\Archived QIRs")]
        public string QIRArchiveDocumentDirectory {
            get {
                return ((string)(this["QIRArchiveDocumentDirectory"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/roi/CONTI.MAIN")]
        public string CSIManageAccount {
            get {
                return ((string)(this["CSIManageAccount"]));
            }
            set {
                this["CSIManageAccount"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\waxfs001\\WAXG-Wahpeton\\Photos\\Employees")]
        public string UsersPhotoDirectory {
            get {
                return ((string)(this["UsersPhotoDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=WAXDB001;User ID=OMNI_SA_SQL;Password=GwdnYaWC}@y\'7+Ks?)XNf*;Connection Ti" +
            "meout=5;MultipleActiveResultSets=True")]
        public string SqlConnectionString {
            get {
                return ((string)(this["SqlConnectionString"]));
            }
        }
    }
}
